//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Обработка_Заявок.DataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Обработка_ЗаявокEntities1 : DbContext
    {
        public Обработка_ЗаявокEntities1()
            : base("name=Обработка_ЗаявокEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вид_Услуги> Вид_Услуги { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Заказчик> Заказчик { get; set; }
        public virtual DbSet<Исполнитель> Исполнитель { get; set; }
        public virtual DbSet<Используемое_Оборудование> Используемое_Оборудование { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
    }
}
