//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Обработка_Заявок.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказчик
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказчик()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Код_Заказчика { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Объект { get; set; }
        public Nullable<int> Код_Города { get; set; }
        public string Улица { get; set; }
    
        public virtual Город Город { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
