//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Обработка_Заявок.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Код_Заказа { get; set; }
        public Nullable<int> Код_Услуги { get; set; }
        public string Краткое_описание { get; set; }
        public Nullable<int> Код_исполнителя { get; set; }
        public Nullable<int> Код_заказчика { get; set; }
        public Nullable<int> Код_оборудования { get; set; }
        public Nullable<int> КолВо_Оборудования { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<int> Код_Статуса { get; set; }
        public string СерийныйНомер { get; set; }
    
        public virtual Вид_Услуги Вид_Услуги { get; set; }
        public virtual Заказчик Заказчик { get; set; }
        public virtual Исполнитель Исполнитель { get; set; }
        public virtual Используемое_Оборудование Используемое_Оборудование { get; set; }
        public virtual Статус Статус { get; set; }
    }
}
